메인배너 Slider 컴포넌트 생성
jnny1017/clone pull request #3
Opened 2022-03-10 10:49 UTC by jnny1017

<img width="1336" alt="스크린샷 2022-03-10 오후 7 44 29" src="https://user-images.githubusercontent.com/16675922/157645668-58cde39d-61d5-41cd-81e4-2bbc195e91b5.png">

swiper 라이브러리 사용하여 메인 배너 오토 슬라이더/클릭 슬라이더를 생성했습니다.
데이터는 api에서 그대로 가져와 사용했습니다.

[👩🏻‍💻 To-dos]
- 화살표, 네비게이션 스타일 추가

2022-03-10 14:09 UTC, addiescode-sj requested changes
윤선님, 첫 PR 축하드립니다! 🙏

크게 페이지레벨을 분리하는 법, destruction을 이용하는법정도만 눈에 띄게 고칠만한 수정사항인것 같아 
이 부분을 코멘트로 달아드렸어요.  꾸준히 나머지 기능 개발 진행해보시면 될 것 같네요. 수고 많으셨어요!

2022-03-10 14:09 UTC, addiescode-sj commented on src/interface/mainBanner.interface.ts
> +export interface MainBanner {
interface 폴더도 위에서 리뷰 드린것과 마찬가지로 main페이지에서만 쓰이는거라면 
src/ pages / main / models라는 디렉토리를 만들어서, `mainBanner.model.ts` 파일에 위치하면 좋을 것 같습니다!

2022-03-10 14:09 UTC, addiescode-sj commented on src/pages/Main/MainPage.tsx
> +      <Slider
Slider를 공용으로 빼두신 시도는 아주 굳! 👍
Slider 컴포넌트가 공용컴포넌트인만큼 지금처럼 수정에는 닫혀있고 확장에는 열려있게끔 유지해주시면 좋으실 것 같아요. 다른 페이지에서 나타나는 슬라이더들이 살짝씩 스타일이 다른거라면 해당 스타일을 그룹화해서 추후에 Slider 컴포넌트에서 분기되어 적용하는 방식도 좋을 것 같고요!

2022-03-11 00:07 UTC, jnny1017 commented on src/components/Slider/Slider.tsx
> +      {slides.data.map((slide: { id: string, image_url: string }, index: number) => (
넵 간결하게 수정했습니다~!

2022-03-11 00:08 UTC, jnny1017 commented on src/fixtures/mainBanner.ts
> +export const mainBannerFixture = {
페이지 레벨에 접근하는 것이 더 보기가 편하겠네요 수정하겠습니다!

2022-03-11 00:08 UTC, jnny1017 commented on src/interface/mainBanner.interface.ts
> +export interface MainBanner {
네 요기도 마찬가지로 수정할게요 models는 어떤 의미인가요??

2022-03-11 02:05 UTC, addiescode-sj commented on src/interface/mainBanner.interface.ts
> +export interface MainBanner {
아하 네 보통 type들이 모아져있는 파일을 ~.model.ts로 붙여주는 편인데, 그 용어를 쓰는 이유는 프로그래밍에서 model이라는 용어 자체가 어떤 관심사에 대해서 소프트웨어에서 캡슐화를 시킨 형태를 띄고있을때 붙여주는 단어이기 때문인데, 또 타입스크립트의 interface와 type은 더욱이 가지고있는 property나 method들이 해당  interface/ type을 설명하기때문에 model 이라는 용어를 쓴다고 생각하시면 좋을 듯 합니다! :)

2022-03-11 02:07 UTC, addiescode-sj approved these changes
확인했습니다 수고하셨어요 !~ 
궁금해하셨던 질문인 왜 models > ~.model.ts 같은 디렉토리와 파일명을 지어주는지에 관해 답변 달아드렸어요. 꼼꼼히 보시면서 반영해주시고 PR 머지하시면 좋을 듯 합니다!

2022-03-11 15:35 UTC, jnny1017 commented on src/interface/mainBanner.interface.ts
> +export interface MainBanner {
네 자세한 설명감사합니다!

2022-03-11 15:35 UTC, merged